### ISSUE TITLE
U-turn bug?

### ISSUE THREAD

**Issue by Allex56** [pimarc/pms50-gns530#62] opened 2021-09-26 11:20 UTC
Hello Pimarc! I had a U-turn bug. I flew LDLO (SID 02 CRE4F) BIMSI (approach VORDME 32 RI, transition RI2 - loaded) LDRI. The autopilot reached CRE and turned to BIMSI. Before reaching 3.4 nm to BIMSI, I activated approach and the autopilot turned around and flew to CRE. On CRE the autopilot turned around and flew to execute the approach scheme, which the autopilot performed correctly. Thank you.
![for developer](https://user-images.githubusercontent.com/91329575/134805441-792dacf2-f807-4043-a43f-a2efbfada443.png)

**Comment by pimarc** [comment] 2021-09-26 11:58
Absolutely no issue with this flight plan on my side. There is no u-turn here.
When you activate the approach, all the en-route waypoints, including CRE should be removed (this is the u-turn bug workaround) so there is no way for the plane to go back to CRE.
Are you sure you have not disabled the u-turn bug workaround in the GNS530 Mod config file?
Thank you to send a screenshot of your flight plan page after you have activated the approach.
You should have something like that:
![test3](https://user-images.githubusercontent.com/59776438/134806887-ac17cb45-34de-4354-9a02-4b649164e926.jpg)

**Comment by Allex56** [comment] 2021-09-26 14:24
You wrote in the description: "This FS2020 error probably drove many of us crazy. This happens when you select / activate an approach after passing the last waypoint. After that the autopilot returns to the last waypoint of the route before reaching the first waypoint. approach.
To eliminate this error, all waypoints in this situation are deleted. This is not a problem since you have already flown these waypoints. "

I did not delete the passed points.
Probably, I did not understand and thought that the passed points will be deleted automatically. I flew the same route again and removed the points manually. After passed CRE and before BIMSI, I removed the CRE and after that activated the approach. The autopilot did not return to CRE and flew to IAF RI. 
I am sorry to have given you the wrong information before doing this. :-( Many thanks for your work!

**Comment by pimarc** [comment] 2021-09-26 14:30
The GN530 Mod automatically removes the enroute waypoints when you activate an approach. You don't have to remove anything manually. Are you sure you are using the GNS530 Mod?

**Comment by Allex56** [comment] 2021-09-26 14:34
Yes. I downloaded here
![Разработчику](https://user-images.githubusercontent.com/91329575/134812268-11a0f246-5790-4314-9428-a812c6b40949.jpg)

**Comment by pimarc** [comment] 2021-09-26 14:40
There is something wrong somewhere because I can't reproduce that issue and it's sure at 100% that any approach activation removes all the enroute waypoints. After activating the approach on the GPS, you should have only the origin, the destination and the approach waypoints, nothing else.

**Comment by pimarc** [comment] 2021-09-26 14:41
Thank you to send a screenshot of your flight plan page after you have activated the approach in the GPS.

**Comment by Allex56** [comment] 2021-09-26 14:47
I'll try again to fly and record a video, I'll make a timecode and send you a link.

**Comment by Allex56** [comment] 2021-09-26 18:00
Pimarc, this is test GNS530 with timecode. If you want me to do something else, please let me know. Thanks. https://www.youtube.com/watch?v=UFLFAE6hvFQ

**Comment by pimarc** [comment] 2021-09-26 18:07
Did you set a config file for the GNS530 and if yes, may I see it?

**Comment by Allex56** [comment] 2021-09-26 18:14
https://drive.google.com/file/d/1axrbDaPzuUi36Z-gOVssD_9FKRx9wb-0/view?usp=sharing

**Comment by pimarc** [comment] 2021-09-26 18:24
This is the example_config.json, not the config.json file.
Verify of you don't have a confgi.json file in the Config/pms50-gns530 direcotry of the GNS530 mod or in the GNS530 data mod if you use it.

To test if the workaround of the u-turn bug is working, you don't need to fly.
Just set a flight plan with an origin, a destination an enroute waypoint and an approach.
Then activate the approach. The enroute waypoint should then be removed.

**Comment by Allex56** [comment] 2021-09-27 07:57
I'm not sure. I think, I have not confgi.json file in the Config/pms50-gns530 direcotry of the GNS530 mod. I don't know what the GNS530 data mod is. I probably don't use it. Please watch a short video overview of the folder where MSFS2020 and GNS530 are installed.
https://user-images.githubusercontent.com/91329575/134866906-eac619aa-4581-4df7-a37c-f051e57d1651.mp4

**Comment by pimarc** [comment] 2021-09-27 08:18
I really don't know.
Try to remove everything in your community folder except navigraph and GNS530.
A simple test to see if the u-turn bug workaround is active:
From the world map, set departure to LFRK. Start flight (no need to take off).
In the GPS set LFRN as destination and add the waypoint GILRA as an enroute waypoint.
So the flight plan is LFRK GILRA LFRN.
Load the approach ILS 28 transition SAMPO. Just load do not activate it.
Then activate the approach: the first approach leg must then be active (LFRK SAMPO) and the GILRA waypoint has been removed from the flight plan.

**Comment by Allex56** [comment] 2021-09-27 10:07
I did as you wrote. The result is as you predicted. See the screen. I will
fly this route. I am wondering how this will be accomplished. Then I will
write you the result.

пн, 27 сент. 2021 г. в 11:18, pimarc ***@***.***>:

**Comment by Allex56** [comment] 2021-09-27 11:24
I turned ON the autopilot at the beginning of the flight and it flew the
route LFRK GILRA LFRN and approach ILS 28 transition SAMPO correctly. I
will try to fly the LDLO BIMSI LDRI route again with departure and
approach. Thanks.

пн, 27 сент. 2021 г. в 13:06, Александр Злоцкий ***@***.***>:

**Comment by Allex56** [comment] 2021-09-27 16:17
I flew out from LDLO to CRE. Without reaching CRE, I loaded approach ILS
14,  but did not activate. After that, BIMSI was removed. But after
reaching CRE, the autopilot flew to BIMSI, which was no longer on the
display and in the flight plan. After reaching BIMSI, the autopilot flew 5
miles from BIMSI to LDRI. After flying 5 miles from BIMSI, I activated the
approach. After that the autopilot turned back to BIMSI. After reaching
BIMSI, the autopilot turned around and flew towards IAF CI14. I tuned the
frequencies to 108.50 on the course glide and on the GNS. I set the course
140 on the course glide device and on [image: image.png] (I don't know what
this device is called in English). When the autopilot finished turning in
the direction of RWY14, I switched from GPS to VLOC system. The course
glide system captured the horizon and the glide path, but the GNS530 and
DME did not capture the signals. This is an enchanted airport. Also in the
simulator on the turn-in track, incorrect heights. I almost collided with a
mountain, although I was flying at the altitude indicated on the LNM map. I
had to turn off the autopilot, gain altitude and turn away from the
mountain. The map shows how I flew away from the track. I won't fly here
anymore. :-)
All the best and success in development!

пн, 27 сент. 2021 г. в 14:23, Александр Злоцкий ***@***.***>:

**Comment by Allex56** [comment] 2021-09-29 06:09
Hello, Pimarc! When I enter a flight plan manually, it often resets some of
the entered waypoints or the entire flight plan, and only departure and
arrival airports are saved. This has been going on for a long time. If you
do not mind, I will inform you by mail if there are any failures in the GNS
530.

пн, 27 сент. 2021 г. в 19:17, Александр Злоцкий ***@***.***>:

**Comment by Allex56** [comment] 2021-10-05 09:37
Hello, Pimarc! I recorded another turn-back video (30 minutes). In my
comment under this video there is a time code. This happens all the time in
a situation like this. There are a lot of unnecessary things in it that you
can skip. I did not cut out too much so that you can see all my actions, if
you need it. Maybe I'm doing something wrong. It cannot be that this
mistake cannot be corrected. I hope you can correct this very significant
error. This mistake makes me crazy. The default GNS 530 also has this
error. Thank you for trying to improve the GNS 530.
https://youtu.be/iIqCSf_-ULk

ср, 29 сент. 2021 г. в 09:08, Александр Злоцкий ***@***.***>:

**Comment by pimarc** [comment] 2021-10-05 10:57
I really don't understand what you are trying to do here. Why do you switch to HDG and then VLOC?
Since TOP is your first approach waypoint, you should activate the approach a few NM before TOP and let the GPS to GPS mode. If you switch it to VLOC at this time, the autopilot will try to follow the VOR or ILS defined by the COM1 frequency and it will not follow your GPS.
I don't see any issue at the GPS level here. Just let the GPS drive the autopilot, eventually set the correct leg if the sim is not able to find the correct one, and activate VLOC (and autopilot approach mode) just before reaching the FAF if this is an ILS approach.

**Comment by Allex56** [comment] 2021-10-05 14:24
My flight plan is LIMF to LFMN. SID 18 TOP6B transition AST8L. The last SID
point is ASTIG. Suppose that the dispatcher allowed me to shorten the way
and not fly to ASTIG. I think, in reality, such a case may be, and I
decided to simulate it. So I turned OFF GPS mode and turned ON HDG to turn
from TOP towards LFMN. Finishing the turn from TOP towards LFMN, I turned
ON the VLOC mode to fly from TOP along the radial 195. Therefore, when I
reached TOP, I turned OFF the GPS and turned ON the HDG and then VLOC
modes. When I got to radial 195 from TOP, I loaded the Approach ILS 04L
transition AMGEL. After flying a little, I first activated the Approach ILS
04L transition AMGEL and then turned ON the GPS mode, but the autopilot did
not fly to AMGEL, but returned to TOP. Only after reaching TOP did the
autopilot fly correctly towards AMGEL.

вт, 5 окт. 2021 г. в 13:57, pimarc ***@***.***>:

**Comment by pimarc** [comment] 2021-10-05 16:01
Ok, I can see what happens here.
This is a sim issue that occurs when you have loaded your approach. The sim then removes the TOP, MIRAX and ASTIG waypoints from the departure procedure (why? I don't know, ask Asobo) but in fact they keep them hidden in the background (and we don't see them at the SDK level).
When you activate the approach, we try to remove the enroute waypoints (uturn bug workaround) but we remove only the one we have access and the sim then restores some of these hidden background waypoints (here TOP).
I don't know if we can manage this situation by a workaround. Anyway we have to wait for SU6 because, as scheduled, the u-turn bug should be fixed so we'll not need any workaround here.
I keep your example as a test.

**Comment by pimarc** [comment] 2021-10-05 16:49
If you want you can try that workaround. Any feedback is welcome.
Replace the file pms50-gns530\html_ui\Pms50\Pages\VCockpit\Instruments\NavSystems\GPS\Shared\BaseGPS.js but he one as attachment after renaming it from.txt to .js (github doesn't accept js files).
[BaseGPS.txt](https://github.com/pimarc/pms50-gns530/files/7287670/BaseGPS.txt)
.

**Comment by Allex56** [comment] 2021-10-06 06:45
Many thanks. You can use my example as you like. I will try to use the
BaseGPS.txt file. How do I know that US6 has been created, although I don't
know what it is? Do you know when you are expected to receive US6? I will
be more attentive at this time. Will US6 be released with the Carenado M20R
update via the Microsoft Store?

вт, 5 окт. 2021 г. в 19:50, pimarc ***@***.***>:

**Comment by Allex56** [comment] 2021-10-29 18:30
Hi. Yes, SU6 solved this problem. Thanks. But there is another malfunction
associated with the VOR approach. Of course, I don't know the reason for
this. I will report this issue tomorrow or the day after tomorrow.

пт, 29 окт. 2021 г. в 19:00, pimarc ***@***.***>:

**Comment by Allex56** [comment] 2021-10-31 08:04
Hi, Pimarc! I rarely use the VOR approach. I flew EBBR to EBAW and found
the VORDME 11 approach was not working. I thought it was a GNS530
malfunction. Unfortunately, I hastened to inform you about this. Sorry.
Later I thought that other VOR approaches should be tested at other
airports. I flew three routes to other airports using VOR approach and
everything was OK. I think VORDME approach 11 in EBAW has a simulator bug.
I like how your GNS530 works now. I made a video of Approach VORDME 11 in a
short cut. https://www.youtube.com/watch?v=mp7SjGm-98s
Thanks a lot for your work! Sincerely, Alexander.

пт, 29 окт. 2021 г. в 21:30, Александр Злоцкий ***@***.***>:

**Closed** 2021-11-01 09:11 UTC

**Comment by Allex56** [comment] 2021-11-04 07:46
Hello Pimarc! I flew EKRS - EKCH. At EKCH airport the autopilot does not
fly any approach pattern in GPS mode. Any patterns are loaded into GNS and
displayed on the display, but the autopilot does not fly the pattern in GNS
mode, although there is ILS and VOR beacon capture. Is this a MSFS2020 bug?
If so, I will report this bug to the MSFS20202 developers.

Regards Alexander.

пн, 1 нояб. 2021 г. в 11:11, pimarc ***@***.***>:
